---
global:
  evaluation_interval: 20s
  scrape_interval: 20s
  scrape_timeout: 15s
scrape_configs:
  -
    job_name: kafka
    static_configs:
      -
        targets:
          - "kafka:7071"
  -
    job_name: kafka-exporter
    static_configs:
      -
        targets:
          - "kafka-exporter:9308"
  -
    job_name: grafana
    static_configs:
      -
        targets:
          - "grafana:3000"
  -
    job_name: prometheus
    static_configs:
      -
        targets:
          - "prometheus:9090"
